### Site Settings ###
title               : Programming Patterns Logic
description         : >-                               # >- means to ignore newlines until "url:"
                      Nisar Ahmed
url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : mahmednisar/code    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

### Author Info ###
author:
  name              : Nisar Ahmed
  image             : /assets/image/patterns.png
  head              : /assets/image/patterns.png
  email             : ahmed.04786@gmail.com
  facebook          : anisar840
  github            : mahmednisar
  hackerrank        : mahmednisar
  instagram         : mahmednisar
  linkedin          : mahmednisar
  medium            : mahmednisar
  telegram          : mahmednisar
  twitter           : mahmednisar
  whatsapp          : +919587991487
  stackoverflow     : 16655875


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: concept/:title


### Collections ###
collections:
  
  links:
    output: true
    permalink: /links/:name




### Exclude from processing ###
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
